version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27018:27017"
  app:
    # build: .
    image: user-management-service-node-mongo
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo